In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('../Data/data.csv')
df.head()

,Timestamp,Date,Symbol,Open,High,Low,Close,Volume BTC,Volume USD
0,1676939580000,2023-02-21 00:33:00,BTC/USD,24859.34,24859.34,24859.34,24859.34,0.000000,0.000000
1,1676939520000,2023-02-21 00:32:00,BTC/USD,24821.96,24859.34,24821.96,24859.34,0.103099,2562.977818
2,1676939460000,2023-02-21 00:31:00,BTC/USD,24818.09,24821.96,24815.47,24821.96,0.090640,2249.866178
3,1676939400000,2023-02-21 00:30:00,BTC/USD,24812.25,24818.09,24812.25,24818.09,0.002203,54.681450
4,1676939340000,2023-02-21 00:29:00,BTC/USD,24809.27,24812.25,24809.27,24812.25,0.090675,2249.862431

In [19]:
df.describe()

,Timestamp,Open,High,Low,Close,Volume BTC,Volume USD
count,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06
mean,9.633091e+11,1.497170e+04,1.497938e+04,1.496394e+04,1.497171e+04,2.082630e+00,2.390526e+04
std,7.879469e+11,1.658607e+04,1.659550e+04,1.657636e+04,1.658607e+04,1.681797e+01,1.135481e+05
min,1.444312e+09,0.000000e+00,2.425000e+02,0.000000e+00,2.360000e+02,0.000000e+00,0.000000e+00
25%,1.500813e+09,2.750000e+03,2.750650e+03,2.749840e+03,2.750000e+03,0.000000e+00,0.000000e+00
50%,1.560047e+12,8.493230e+03,8.497840e+03,8.489520e+03,8.493240e+03,7.482203e-02,8.237107e+02
75%,1.620006e+12,2.038378e+04,2.039286e+04,2.037482e+04,2.038379e+04,9.309989e-01,1.142039e+04
max,1.676940e+12,6.899887e+04,6.900000e+04,6.878700e+04,6.899887e+04,8.264463e+03,3.749580e+07

In [20]:
df.isna().sum()

Timestamp     0
Date          0
Symbol        0
Open          0
High          0
Low           0
Close         0
Volume BTC    0
Volume USD    0
dtype: int64

In [21]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

In [22]:
df_4h = df.resample('4H').agg({
    'Open' : 'first',
    'High' : 'max',
    'Low' : 'min',
    'Close' : 'last',
    'Volume BTC' : 'sum',
    'Volume USD' : 'sum'
})
df_4h.dropna(inplace=True)
df_4h.head()

C:\Users\User\AppData\Local\Temp\ipykernel_202536\613425973.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_4h = df.resample('4H').agg({

                       Open    High    Low   Close  Volume BTC   Volume USD
Date
2015-10-08 12:00:00    0.00  245.00    0.0  244.92    8.077229  1977.745452
2015-10-08 16:00:00  244.92  244.99  244.0  244.00   13.037812  3187.597961
2015-10-08 20:00:00  244.00  244.00  243.6  243.95   10.639661  2595.066878
2015-10-09 00:00:00  243.95  243.95  243.6  243.60    3.000000   730.800000
2015-10-09 04:00:00  243.60  243.60  243.6  243.60    0.000000     0.000000

In [23]:
df_4h['Target'] = df_4h['Close'].shift(-1)
df_4h.head()

,Open,High,Low,Close,Volume BTC,Volume USD,Target
Date,,,,,,,
2015-10-08 12:00:00,0.00,245.00,0.0,244.92,8.077229,1977.745452,244.00
2015-10-08 16:00:00,244.92,244.99,244.0,244.00,13.037812,3187.597961,243.95
2015-10-08 20:00:00,244.00,244.00,243.6,243.95,10.639661,2595.066878,243.60
2015-10-09 00:00:00,243.95,243.95,243.6,243.60,3.000000,730.800000,243.60
2015-10-09 04:00:00,243.60,243.60,243.6,243.60,0.000000,0.000000,243.63

In [25]:
df_4h.dropna(inplace=True)
df_4h.isna().sum()

Open          0
High          0
Low           0
Close         0
Volume BTC    0
Volume USD    0
Target        0
dtype: int64

In [26]:
df_4h["Close1"] = df_4h["Close"].shift(1)
df_4h["Close2"] = df_4h["Close"].shift(2)
df_4h["Close3"] = df_4h["Close"].shift(3)
df_4h.dropna(inplace=True)
df_4h.head()

,Open,High,Low,Close,Volume BTC,Volume USD,Target,Close1,Close2,Close3
Date,,,,,,,,,,
2015-10-09 00:00:00,243.95,243.95,243.60,243.60,3.000000,730.800000,243.60,243.95,244.00,244.92
2015-10-09 04:00:00,243.60,243.60,243.60,243.60,0.000000,0.000000,243.63,243.60,243.95,244.00
2015-10-09 08:00:00,243.60,243.75,243.60,243.63,1.000000,243.630000,244.00,243.60,243.60,243.95
2015-10-09 12:00:00,243.63,244.00,243.63,244.00,8.145083,1987.400204,244.06,243.63,243.60,243.60
2015-10-09 16:00:00,244.00,244.06,243.70,244.06,3.662625,893.877805,245.39,244.00,243.63,243.60

In [38]:
df_4h["SMA7"] = df_4h.rolling(window=7)['Close'].mean()
df_4h["SMA14"] = df_4h.rolling(window=14)['Close'].mean()
df_4h.dropna(inplace=True)
df_4h.head()

,Open,High,Low,Close,Volume BTC,Volume USD,Target,Close1,Close2,Close3,SMA7,SMA14
Date,,,,,,,,,,,,
2015-10-11 04:00:00,246.30,246.30,246.30,246.30,0.000000,0.000000,246.30,246.30,246.3,245.37,245.670000,244.962857
2015-10-11 08:00:00,246.30,246.30,246.30,246.30,0.000000,0.000000,246.30,246.30,246.3,246.30,245.791429,245.155714
2015-10-11 12:00:00,246.30,246.30,246.30,246.30,0.000000,0.000000,248.24,246.30,246.3,246.30,246.034286,245.348571
2015-10-11 16:00:00,246.30,248.24,245.96,248.24,10.564829,2607.308871,249.50,246.30,246.3,246.30,246.444286,245.677857
2015-10-11 20:00:00,248.24,249.50,247.77,249.50,3.841956,954.048804,248.98,248.24,246.3,246.30,247.034286,246.070714