In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [100]:
df = pd.read_csv('../Data/data.csv')
df.head()

,Timestamp,Date,Symbol,Open,High,Low,Close,Volume BTC,Volume USD
0,1676939580000,2023-02-21 00:33:00,BTC/USD,24859.34,24859.34,24859.34,24859.34,0.000000,0.000000
1,1676939520000,2023-02-21 00:32:00,BTC/USD,24821.96,24859.34,24821.96,24859.34,0.103099,2562.977818
2,1676939460000,2023-02-21 00:31:00,BTC/USD,24818.09,24821.96,24815.47,24821.96,0.090640,2249.866178
3,1676939400000,2023-02-21 00:30:00,BTC/USD,24812.25,24818.09,24812.25,24818.09,0.002203,54.681450
4,1676939340000,2023-02-21 00:29:00,BTC/USD,24809.27,24812.25,24809.27,24812.25,0.090675,2249.862431

In [101]:
df.describe()

,Timestamp,Open,High,Low,Close,Volume BTC,Volume USD
count,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06,3.766763e+06
mean,9.633091e+11,1.497170e+04,1.497938e+04,1.496394e+04,1.497171e+04,2.082630e+00,2.390526e+04
std,7.879469e+11,1.658607e+04,1.659550e+04,1.657636e+04,1.658607e+04,1.681797e+01,1.135481e+05
min,1.444312e+09,0.000000e+00,2.425000e+02,0.000000e+00,2.360000e+02,0.000000e+00,0.000000e+00
25%,1.500813e+09,2.750000e+03,2.750650e+03,2.749840e+03,2.750000e+03,0.000000e+00,0.000000e+00
50%,1.560047e+12,8.493230e+03,8.497840e+03,8.489520e+03,8.493240e+03,7.482203e-02,8.237107e+02
75%,1.620006e+12,2.038378e+04,2.039286e+04,2.037482e+04,2.038379e+04,9.309989e-01,1.142039e+04
max,1.676940e+12,6.899887e+04,6.900000e+04,6.878700e+04,6.899887e+04,8.264463e+03,3.749580e+07

In [102]:
df.isna().sum()

Timestamp     0
Date          0
Symbol        0
Open          0
High          0
Low           0
Close         0
Volume BTC    0
Volume USD    0
dtype: int64

In [103]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')

In [104]:
df_4h = df.resample('4H').agg({
    'Open' : 'first',
    'High' : 'max',
    'Low' : 'min',
    'Close' : 'last',
    'Volume BTC' : 'sum',
    'Volume USD' : 'sum'
})
df_4h.dropna(inplace=True)
df_4h.head()

C:\Users\User\AppData\Local\Temp\ipykernel_189208\613425973.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df_4h = df.resample('4H').agg({

                       Open    High    Low   Close  Volume BTC   Volume USD
Date
2015-10-08 12:00:00    0.00  245.00    0.0  244.92    8.077229  1977.745452
2015-10-08 16:00:00  244.92  244.99  244.0  244.00   13.037812  3187.597961
2015-10-08 20:00:00  244.00  244.00  243.6  243.95   10.639661  2595.066878
2015-10-09 00:00:00  243.95  243.95  243.6  243.60    3.000000   730.800000
2015-10-09 04:00:00  243.60  243.60  243.6  243.60    0.000000     0.000000

In [105]:
df_4h['Target'] = df_4h['Close'].shift(-1)
df_4h.head()

,Open,High,Low,Close,Volume BTC,Volume USD,Target
Date,,,,,,,
2015-10-08 12:00:00,0.00,245.00,0.0,244.92,8.077229,1977.745452,244.00
2015-10-08 16:00:00,244.92,244.99,244.0,244.00,13.037812,3187.597961,243.95
2015-10-08 20:00:00,244.00,244.00,243.6,243.95,10.639661,2595.066878,243.60
2015-10-09 00:00:00,243.95,243.95,243.6,243.60,3.000000,730.800000,243.60
2015-10-09 04:00:00,243.60,243.60,243.6,243.60,0.000000,0.000000,243.63

In [106]:
df_4h.dropna(inplace=True)
df_4h.isna().sum()

Open          0
High          0
Low           0
Close         0
Volume BTC    0
Volume USD    0
Target        0
dtype: int64

In [107]:
df_4h["Close1%"] = (df_4h["Close"].shift(1) - df_4h["Close"]) / df_4h["Close"] * 100
df_4h["Close2%"] = -1 * (df_4h["Close"].shift(2) - df_4h["Close"]) / df_4h["Close"] * 100
df_4h["Close3%"] = -1 * (df_4h["Close"].shift(3) - df_4h["Close"]) / df_4h["Close"] * 100
df_4h["Close_day%"] = -1 * (df_4h["Close"].shift(7) - df_4h["Close"]) / df_4h["Close"] * 100

df_4h["Body%"] = -1 * (df_4h["Close"] - df_4h["Open"]) / df_4h["Close"] * 100
df_4h["Movement"] = df_4h["High"] - df_4h["Low"]
df_4h["Movement%"]  = ((df_4h["High"] - df_4h["Low"]) / df_4h["Close"]) * 100
df_4h["mvm_avg7%"]  = df_4h.rolling(window=7)["Movement%"].mean()
df_4h["mvm_avg14%"] = df_4h.rolling(window=14)["Movement%"].mean()

df_4h["SMA7%"]  = (df_4h.rolling(window=7)['Close'].mean() - df_4h['Close']) / df_4h['Close'] * 100
df_4h["SMA14%"] = (df_4h.rolling(window=14)['Close'].mean() - df_4h['Close']) / df_4h['Close'] * 100
df_4h["SMA21%"] = (df_4h.rolling(window=21)['Close'].mean() - df_4h['Close']) / df_4h['Close'] * 100
df_4h.dropna(inplace=True)
df_4h.head()

,Open,High,Low,Close,Volume BTC,Volume USD,Target,Close1%,Close2%,Close3%,Close_day%,Body%,Movement,Movement%,mvm_avg7%,mvm_avg14%,SMA7%,SMA14%,SMA21%
Date,,,,,,,,,,,,,,,,,,,
2015-10-11 20:00:00,248.24,249.50,247.77,249.50,3.841956,954.048804,248.98,-0.505010,1.282565,1.282565,1.655311,-0.505010,1.73,0.693387,0.284206,0.403625,-0.988262,-1.374463,-1.656837
2015-10-12 00:00:00,249.50,249.50,248.98,248.98,8.340306,2076.577525,248.71,0.208852,0.297213,1.076392,1.076392,0.208852,0.52,0.208852,0.260101,0.408007,-0.627704,-1.027334,-1.373796
2015-10-12 04:00:00,248.98,248.98,248.71,248.71,0.230000,57.203300,247.72,0.108560,-0.317639,0.188975,0.969000,0.108560,0.27,0.108560,0.275609,0.243732,-0.381397,-0.824540,-1.176547
2015-10-12 08:00:00,248.71,248.71,247.72,247.72,11.060274,2741.613524,247.62,0.399645,-0.508639,-0.718553,0.573228,0.399645,0.99,0.399645,0.332701,0.267914,0.098614,-0.364467,-0.709134
2015-10-12 12:00:00,247.72,247.90,247.62,247.62,30.968000,7669.163180,247.60,0.040384,-0.440191,-0.549229,0.533075,0.040384,0.28,0.113076,0.348855,0.249508,0.215191,-0.261634,-0.591728

In [109]:
df_4h["Target"] = (df_4h["Target"] - df_4h["Close"]) / df_4h["Close"] * 100

df_4h.head(20)

,Open,High,Low,Close,Volume BTC,Volume USD,Target,Close1%,Close2%,Close3%,Close_day%,Body%,Movement,Movement%,mvm_avg7%,mvm_avg14%,SMA7%,SMA14%,SMA21%
Date,,,,,,,,,,,,,,,,,,,
2015-10-11 20:00:00,248.24,249.50,247.77,249.50,3.841956,954.048804,-0.208417,-0.505010,1.282565,1.282565,1.655311,-0.505010,1.73,0.693387,0.284206,0.403625,-0.988262,-1.374463,-1.656837
2015-10-12 00:00:00,249.50,249.50,248.98,248.98,8.340306,2076.577525,-0.108442,0.208852,0.297213,1.076392,1.076392,0.208852,0.52,0.208852,0.260101,0.408007,-0.627704,-1.027334,-1.373796
2015-10-12 04:00:00,248.98,248.98,248.71,248.71,0.230000,57.203300,-0.398054,0.108560,-0.317639,0.188975,0.969000,0.108560,0.27,0.108560,0.275609,0.243732,-0.381397,-0.824540,-1.176547
2015-10-12 08:00:00,248.71,248.71,247.72,247.72,11.060274,2741.613524,-0.040368,0.399645,-0.508639,-0.718553,0.573228,0.399645,0.99,0.399645,0.332701,0.267914,0.098614,-0.364467,-0.709134
2015-10-12 12:00:00,247.72,247.90,247.62,247.62,30.968000,7669.163180,-0.008077,0.040384,-0.440191,-0.549229,0.533075,0.040384,0.28,0.113076,0.348855,0.249508,0.215191,-0.261634,-0.591728
2015-10-12 16:00:00,247.62,247.91,247.60,247.60,6.608900,1636.976238,0.000000,0.008078,-0.048465,-0.448304,0.525040,0.008078,0.31,0.125202,0.366741,0.233630,0.298292,-0.167032,-0.506770
2015-10-12 20:00:00,247.60,247.61,247.60,247.60,5.580000,1381.609000,-0.747173,0.000000,-0.008078,-0.048465,-0.258481,-0.000000,0.01,0.004039,0.236109,0.210630,0.261366,-0.102700,-0.430418
2015-10-13 00:00:00,247.60,247.60,245.75,245.75,16.600569,4096.506460,0.915565,0.752798,-0.752798,-0.760936,-1.525941,0.752798,1.85,0.752798,0.244596,0.264401,0.798140,0.660369,0.353049
2015-10-13 04:00:00,245.75,248.00,245.75,248.00,18.342363,4536.009201,1.963710,-0.907258,0.161290,0.161290,-0.395161,-0.907258,2.25,0.907258,0.344368,0.302234,-0.172811,-0.203917,-0.481759
2015-10-13 08:00:00,248.00,252.87,248.00,252.87,30.575771,7637.152814,-0.818602,-1.925891,2.815676,2.084075,1.645114,-1.925891,4.87,1.925891,0.603987,0.439798,-1.860357,-1.940297,-2.257512
2015-10-13 12:00:00,252.87,252.87,250.80,250.80,24.666922,6195.177750,-0.179426,0.825359,1.116427,2.013557,1.228070,0.825359,2.07,0.825359,0.664803,0.498752,-0.874915,-1.002791,-1.350346
2015-10-13 16:00:00,250.80,250.80,249.92,250.35,8.390691,2098.653448,0.027961,0.179748,-1.006591,0.938686,1.090473,0.179748,0.88,0.351508,0.698865,0.523860,-0.540957,-0.709293,-1.079822
2015-10-13 20:00:00,250.35,250.42,250.00,250.42,16.849440,4214.356123,0.231611,-0.027953,-0.151745,-0.978356,1.126108,-0.027953,0.42,0.167718,0.704939,0.535840,-0.407886,-0.619531,-0.996802
2015-10-14 00:00:00,250.42,251.08,250.42,251.00,55.861409,14012.536863,0.000000,-0.231076,0.258964,0.079681,1.354582,-0.231076,0.66,0.262948,0.741926,0.489017,-0.444508,-0.770632,-1.118763
2015-10-14 04:00:00,251.00,251.00,250.70,251.00,49.797974,12489.341014,0.059761,0.000000,0.231076,0.258964,2.091633,-0.000000,0.30,0.119522,0.651458,0.448027,-0.145703,-0.727945,-1.011952
2015-10-14 08:00:00,251.00,251.86,251.00,251.15,34.745968,8727.742483,0.736612,-0.059725,0.059725,0.290663,1.254231,-0.059725,0.86,0.342425,0.570767,0.457568,-0.026165,-0.725520,-0.979115
2015-10-14 12:00:00,251.15,253.00,251.15,253.00,8.196030,2066.442465,0.363636,-0.731225,0.790514,0.790514,0.051383,-0.731225,1.85,0.731225,0.400101,0.502044,-0.749859,-1.330322,-1.577075
2015-10-14 16:00:00,253.00,254.75,253.00,253.92,37.306910,9489.479909,-0.362319,-0.362319,1.090895,1.149968,1.228733,-0.362319,1.75,0.689193,0.380649,0.522726,-0.933927,-1.513413,-1.790778
2015-10-14 20:00:00,253.92,254.19,253.00,253.00,25.648471,6504.133487,0.628458,0.363636,-0.000000,0.731225,1.047431,0.363636,1.19,0.470356,0.397627,0.548246,-0.424054,-1.003388,-1.307548
2015-10-15 00:00:00,253.00,256.15,253.00,254.59,28.856715,7353.200462,0.514553,-0.624534,0.263168,0.624534,1.637928,-0.624534,3.15,1.237283,0.550422,0.627680,-0.811950,-1.425541,-1.768857

In [110]:
X = df_4h.drop('Target', axis=1)
y = df_4h['Target']

X_train = X.iloc[:int(0.8*len(X))]
y_train = y.iloc[:int(0.8*len(y))]
X_test = X.iloc[int(0.8*len(X)):]
y_test = y.iloc[int(0.8*len(y)):]

In [118]:
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, mean_absolute_error

In [126]:
rf_model = RandomForestRegressor(
    n_estimators=101,
    min_samples_leaf=2,
    n_jobs=-1,
    random_state=42
)

In [127]:
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

In [128]:
print("mean sq err :", mean_squared_error(y_test, y_pred))
print("mean absolute err : ", mean_absolute_error(y_test, y_pred))

mean sq err : 1.8214269680986317
mean absolute err :  0.9048813513642436

In [129]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=500,
    learning_rate=0.02,
    max_depth=6,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)
y_pred = xgb_model.predict(X_test)

In [132]:
print("mean sq err :", mean_squared_error(y_test, y_pred))
print("mean absolute err : ", mean_absolute_error(y_test, y_pred))

mean sq err : 1.8121253624230875
mean absolute err :  0.8965167210888139

In [131]:
import optuna
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import numpy as np

def objective(trial):
    param = {
        'objective': 'reg:squarederror',
        'eval_metric': 'rmse',
        # 'tree_method': 'hist',
        'random_state': 42,
        'n_jobs': -1,
        'device': 'gpu',
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5)
    }

    model = xgb.XGBRegressor(**param)

    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        verbose=False
    )

    y_pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    return rmse

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)

print("Best Parameters:", study.best_params)
print("Best RMSE:", study.best_value)

[I 2026-05-24 09:50:29,805] A new study created in memory with name: no-name-915ed505-72f6-46d0-9803-1e48bb6ea380
[I 2026-05-24 09:50:31,798] Trial 0 finished with value: 1.433109533459277 and parameters: {'n_estimators': 470, 'max_depth': 7, 'learning_rate': 0.08856006877574632, 'subsample': 0.8738662513228069, 'colsample_bytree': 0.6226737997867461, 'gamma': 0.07375165692666474}. Best is trial 0 with value: 1.433109533459277.
[I 2026-05-24 09:50:33,111] Trial 1 finished with value: 1.4852298459244206 and parameters: {'n_estimators': 424, 'max_depth': 7, 'learning_rate': 0.15329118824252283, 'subsample': 0.9142913249060667, 'colsample_bytree': 0.9192330912635176, 'gamma': 0.3001376685404712}. Best is trial 0 with value: 1.433109533459277.
[I 2026-05-24 09:50:33,500] Trial 2 finished with value: 1.3188201815171867 and parameters: {'n_estimators': 123, 'max_depth': 7, 'learning_rate': 0.013606432507468302, 'subsample': 0.9297762099050856, 'colsample_bytree': 0.624450175311181, 'gamma': 0.1726585315334973}. Best is trial 2 with value: 1.3188201815171867.
[I 2026-05-24 09:50:34,778] Trial 3 finished with value: 1.3244291984258185 and parameters: {'n_estimators': 429, 'max_depth': 5, 'learning_rate': 0.012994312186868081, 'subsample': 0.7859046741836466, 'colsample_bytree': 0.6329605113517248, 'gamma': 0.4873488905705071}. Best is trial 2 with value: 1.3188201815171867.
[I 2026-05-24 09:50:36,638] Trial 4 finished with value: 1.3470317305313497 and parameters: {'n_estimators': 334, 'max_depth': 9, 'learning_rate': 0.019649514766542784, 'subsample': 0.6203236003949638, 'colsample_bytree': 0.9475009895607405, 'gamma': 0.17687112436647218}. Best is trial 2 with value: 1.3188201815171867.
[I 2026-05-24 09:50:37,102] Trial 5 finished with value: 1.3318896646164917 and parameters: {'n_estimators': 321, 'max_depth': 4, 'learning_rate': 0.0294484102551757, 'subsample': 0.636366357518182, 'colsample_bytree': 0.6325062292681555, 'gamma': 0.2934096261238541}. Best is trial 2 with value: 1.3188201815171867.
[I 2026-05-24 09:50:37,800] Trial 6 finished with value: 1.434615126841166 and parameters: {'n_estimators': 240, 'max_depth': 5, 'learning_rate': 0.1503676076049447, 'subsample': 0.6933768518396607, 'colsample_bytree': 0.7697910709529324, 'gamma': 0.25865613793019043}. Best is trial 2 with value: 1.3188201815171867.
[I 2026-05-24 09:50:38,458] Trial 7 finished with value: 1.3184225869867745 and parameters: {'n_estimators': 274, 'max_depth': 6, 'learning_rate': 0.010334189335897526, 'subsample': 0.8924899407519862, 'colsample_bytree': 0.8098901344818655, 'gamma': 0.024978374891178434}. Best is trial 7 with value: 1.3184225869867745.
[I 2026-05-24 09:50:41,090] Trial 8 finished with value: 1.4131030244598806 and parameters: {'n_estimators': 470, 'max_depth': 8, 'learning_rate': 0.05164724022454492, 'subsample': 0.7325876001138931, 'colsample_bytree': 0.9838390102148391, 'gamma': 0.10106440941508693}. Best is trial 7 with value: 1.3184225869867745.
[I 2026-05-24 09:50:42,518] Trial 9 finished with value: 1.3977842528560556 and parameters: {'n_estimators': 268, 'max_depth': 7, 'learning_rate': 0.09464743079297072, 'subsample': 0.8568118341376159, 'colsample_bytree': 0.6159144814693238, 'gamma': 0.203328434531873}. Best is trial 7 with value: 1.3184225869867745.
[I 2026-05-24 09:50:43,042] Trial 10 finished with value: 1.316776307636743 and parameters: {'n_estimators': 174, 'max_depth': 3, 'learning_rate': 0.010161127797897388, 'subsample': 0.9993093480331141, 'colsample_bytree': 0.7975546322806305, 'gamma': 0.007088515208239637}. Best is trial 10 with value: 1.316776307636743.
[I 2026-05-24 09:50:43,495] Trial 11 finished with value: 1.3169132636778742 and parameters: {'n_estimators': 167, 'max_depth': 3, 'learning_rate': 0.010714962592886443, 'subsample': 0.9974145206591428, 'colsample_bytree': 0.8052382540026666, 'gamma': 0.003193241140450609}. Best is trial 10 with value: 1.316776307636743.
[I 2026-05-24 09:50:43,867] Trial 12 finished with value: 1.3179236407738302 and parameters: {'n_estimators': 135, 'max_depth': 3, 'learning_rate': 0.023829069012110987, 'subsample': 0.9992582545424381, 'colsample_bytree': 0.8304890654410112, 'gamma': 0.005202193424613684}. Best is trial 10 with value: 1.316776307636743.
[I 2026-05-24 09:50:44,338] Trial 13 finished with value: 1.3226680220638953 and parameters: {'n_estimators': 193, 'max_depth': 3, 'learning_rate': 0.039109737360803976, 'subsample': 0.9782172636804652, 'colsample_bytree': 0.7314062395980698, 'gamma': 0.10197246407166413}. Best is trial 10 with value: 1.316776307636743.
[I 2026-05-24 09:50:44,855] Trial 14 finished with value: 1.3186096407975896 and parameters: {'n_estimators': 182, 'max_depth': 4, 'learning_rate': 0.017138152376690953, 'subsample': 0.9537673240941247, 'colsample_bytree': 0.8759413087926983, 'gamma': 0.46508019063726497}. Best is trial 10 with value: 1.316776307636743.
[I 2026-05-24 09:50:45,366] Trial 15 finished with value: 1.3162035031925452 and parameters: {'n_estimators': 192, 'max_depth': 3, 'learning_rate': 0.010189941972459872, 'subsample': 0.8409790231089713, 'colsample_bytree': 0.7348985286814064, 'gamma': 0.054130237653530144}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:46,001] Trial 16 finished with value: 1.3235826956534382 and parameters: {'n_estimators': 216, 'max_depth': 4, 'learning_rate': 0.033751406720485946, 'subsample': 0.8064073371850522, 'colsample_bytree': 0.7054917669019586, 'gamma': 0.3878316123041552}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:46,484] Trial 17 finished with value: 1.328163859684618 and parameters: {'n_estimators': 117, 'max_depth': 5, 'learning_rate': 0.054633081355600695, 'subsample': 0.812579050012229, 'colsample_bytree': 0.6962206705250579, 'gamma': 0.059448920653294324}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:47,333] Trial 18 finished with value: 1.318260992272256 and parameters: {'n_estimators': 378, 'max_depth': 3, 'learning_rate': 0.016633558639215573, 'subsample': 0.7576522445399381, 'colsample_bytree': 0.7556309731333545, 'gamma': 0.13261147487635436}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:48,079] Trial 19 finished with value: 1.321067036930405 and parameters: {'n_estimators': 238, 'max_depth': 4, 'learning_rate': 0.021954454986847373, 'subsample': 0.8477108833811189, 'colsample_bytree': 0.8504647109458614, 'gamma': 0.05419766160333319}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:48,759] Trial 20 finished with value: 1.3179984169892858 and parameters: {'n_estimators': 151, 'max_depth': 6, 'learning_rate': 0.013716747896171956, 'subsample': 0.6896486389112084, 'colsample_bytree': 0.6925294891199565, 'gamma': 0.128150006636015}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:49,183] Trial 21 finished with value: 1.3165522861631247 and parameters: {'n_estimators': 173, 'max_depth': 3, 'learning_rate': 0.010048105479134107, 'subsample': 0.9484447223831026, 'colsample_bytree': 0.783169303948496, 'gamma': 0.00241137495351352}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:49,634] Trial 22 finished with value: 1.3165468831561478 and parameters: {'n_estimators': 201, 'max_depth': 3, 'learning_rate': 0.010155757223498877, 'subsample': 0.9463975475370457, 'colsample_bytree': 0.7706248051206395, 'gamma': 0.04320778215758004}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:50,222] Trial 23 finished with value: 1.3176192787915229 and parameters: {'n_estimators': 217, 'max_depth': 4, 'learning_rate': 0.013126021451157122, 'subsample': 0.9465159124934642, 'colsample_bytree': 0.7514687438185373, 'gamma': 0.0634633256527316}. Best is trial 15 with value: 1.3162035031925452.
[I 2026-05-24 09:50:50,549] Trial 24 finished with value: 1.3156891390746717 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.026395843322402926, 'subsample': 0.8964897103725178, 'colsample_bytree': 0.8761245950636309, 'gamma': 0.1424833450719342}. Best is trial 24 with value: 1.3156891390746717.
[I 2026-05-24 09:50:50,981] Trial 25 finished with value: 1.3178519182654291 and parameters: {'n_estimators': 110, 'max_depth': 5, 'learning_rate': 0.02751027718445001, 'subsample': 0.8358450429820296, 'colsample_bytree': 0.890113424075884, 'gamma': 0.14885636435863986}. Best is trial 24 with value: 1.3156891390746717.
[I 2026-05-24 09:50:51,701] Trial 26 finished with value: 1.3207760901615968 and parameters: {'n_estimators': 285, 'max_depth': 4, 'learning_rate': 0.017523624332621366, 'subsample': 0.8939966509006432, 'colsample_bytree': 0.8548950410193116, 'gamma': 0.21735502360046188}. Best is trial 24 with value: 1.3156891390746717.
[I 2026-05-24 09:50:52,010] Trial 27 finished with value: 1.325843199302312 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.08945139334775327, 'subsample': 0.9072119436729031, 'colsample_bytree': 0.6628424727565442, 'gamma': 0.10030377608229506}. Best is trial 24 with value: 1.3156891390746717.
[I 2026-05-24 09:50:52,447] Trial 28 finished with value: 1.329267579358729 and parameters: {'n_estimators': 140, 'max_depth': 4, 'learning_rate': 0.06005805491208853, 'subsample': 0.8675040014526788, 'colsample_bytree': 0.7300191651911985, 'gamma': 0.043240679900545226}. Best is trial 24 with value: 1.3156891390746717.
[I 2026-05-24 09:50:52,923] Trial 29 finished with value: 1.336007533541869 and parameters: {'n_estimators': 205, 'max_depth': 3, 'learning_rate': 0.06949404069705747, 'subsample': 0.879490421431451, 'colsample_bytree': 0.9111389052226357, 'gamma': 0.0913689849676077}. Best is trial 24 with value: 1.3156891390746717.

Best Parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.026395843322402926, 'subsample': 0.8964897103725178, 'colsample_bytree': 0.8761245950636309, 'gamma': 0.1424833450719342}
Best RMSE: 1.3156891390746717

In [133]:
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    # 'tree_method': 'hist',
    'random_state': 42,
    'n_jobs': -1,
    'device': 'gpu'
}

model = XGBRegressor(**params, **study.best_params)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [138]:
print("mean sq err :", mean_squared_error(y_test, y_pred))
print("mean absolute err : ", mean_absolute_error(y_test, y_pred))

mean sq err : 1.731037910679051
mean absolute err :  0.861448948526991

In [136]:
import pandas_ta as ta